spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: api-gateway
server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
zuul:
  routes:
    customer-provider:
     path: /customer-provider/**
     serviceId: customer-provider
    service-provider:
      path: /service-provider/**
      serviceId: service-provider

