eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
server:
  port: 8082
spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: service-provider
